### PR TITLE
Add some more clickbaits + MutationObserver

### PR DESCRIPTION
**Pull request by gillescastel**
To detect clickbait in async content, we need a `MutationObserver`.

(Is it normal that commits from a previous pull request are added too? Am I doing something wrong?)

### CODE REVIEW

**Comment by mrdoob** [comment]
> (Is it normal that commits from a previous pull request are added too? Am I doing something wrong?)

You basically need to pull from my master before doing new commits. But you merged it already so it's fine.

**Comment by mrdoob** [comment]
Isn't `MutationObserver` deprecated?

**Comment by gillescastel** [comment]
Mutation _Events_ are depreciated. The recommended alternative is using Mutation Observers. [Mutation Events on mdn](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events)

Thank you for your response on my git problem!

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Hey @gillescastel, 

I noticed that `MutationObserver` currently sends all the added nodes to `strikeClickbaitLinks`.

Do you mind changing the code so it only sends nodes with `nodeName === 'A'` to `strikeIfClickbait` instead?

I would do it myself, but I haven't done the jump to ES6, so I'm not sure how the syntax should be.

Thanks!

**Comment by gillescastel** [comment]
With pleasure, but what would be the point of that? AFAIK, we cannot only watch for anchor elements, so we have to process every element added to the DOM. 

`strikeClickbaitLinks` is called on the body on init, and on every new element added to the DOM. As this is called twice in the code, I think it's good to put it in its own function.

Can you clarify your comment?

Have a great day!

**Comment by mrdoob** [comment]
Well, we basically need to only pass "A" nodes to `strikeIfClickbait()`. Right now we're passing any node and that doesn't make sense because we can be passing a textnode that is not clickable and we end up strikethrough random things.

I'm aware that `MutationObserver` can't look for specific node types, but after getting the addedNodes we should filter that and only deal with "A" nodes.

Makes sense?

**Comment by gillescastel** [comment]
We only pass anchor elements to `strikeIfClickbait()`. The only call to `strikeIfClickbait` is:

``` javascript
function strikeClickbaitLinks( element ) {
    const elements = node.getElementsByTagName( 'a' );
    [ ...elements ].forEach( strikeIfClickbait );
}
```

So we only strike clickable elements.

However the added node, which is captured by `MutationObserver`, can be a text node, comment node etc ...  If this is the case, this gives an error because we try to `getElementsByTagName`. Therefore we should filter non-element nodes in `strikeClickbaitLinks`:

``` javascript
function strikeClickbaitLinks( node ) {
    if ( node.nodeType !== 1 ) {
        // node is not an element (text, comment, ...)
        return;
    }

    const elements = node.getElementsByTagName( 'a' );
    [ ...elements ].forEach( strikeIfClickbait );

}
```

The simplest way the filtering of anchor nodes can be done is using `getElementsByTagName`. This is because the nodeList `addedNodes` does not contain each single element added. If `div > a * 5` is added, then `addedNodes` only contains the `div` and not the anchor tags. This means we cannot use `filter` to filter these elements. `getElementsByTagName` seems the best option to get all the children that are anchors. This is what the current code does.

I hope we understand each other correctly. I'll make a pull request if this solves the problem you have.

**Comment by mrdoob** [comment]
Ah, I understand now. Seems like I can't yet read ES6 code...

How about this?

``` js
    const observer = new MutationObserver( function ( mutations ) {

        mutations.forEach( function ( mutation ) {

            mutation.addedNodes.forEach( function ( node ) {

                if ( node.nodeType === 1 ) strikeClickbaitLinks( node );

            } );

        } );

    } );
```

**Comment by gillescastel** [comment]
Seems good to me! (But note that addedNodes is not an array but a node list, so you cannot use forEach)

**Comment by mrdoob** [comment]
> Seems good to me! (But note that addedNodes is not an array but a node list, so you cannot use forEach)

Are you sure? I just tried locally and seems to work fine?

**Comment by gillescastel** [comment]
I'm sorry, you're right. `NodeList` has a forEach, it's `HTMLCollection` that has not. I'll update the pull request!

**Pull request merged**
